#!/usr/bin/env python3
"""
Generate an antialiased 5-point star as an LVGL ALPHA_8BIT image.

LVGL's Montserrat build carries no U+2605, and the built-in symbol font is a
FontAwesome subset with no star in it. Rather than spell out "STARS", we
rasterise one here: alpha-only, so it takes the accent colour at draw time via
img_recolor, and it stays crisp because we generate it at the exact size used.

Run: python3 tools/gen_star.py > include/star_img.h
"""
import math

SIZE = 21          # odd, so the star has a true centre pixel
SS = 4             # supersampling factor per axis
OUTER = SIZE / 2 - 0.5
INNER = OUTER * 0.420

def star_polygon():
    pts = []
    for i in range(10):
        # Start at 12 o'clock and alternate outer/inner vertices.
        angle = -math.pi / 2 + i * math.pi / 5
        r = OUTER if i % 2 == 0 else INNER
        pts.append((SIZE / 2 + r * math.cos(angle), SIZE / 2 + r * math.sin(angle)))
    return pts

def inside(poly, x, y):
    hit = False
    j = len(poly) - 1
    for i in range(len(poly)):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if (yi > y) != (yj > y):
            if x < (xj - xi) * (y - yi) / (yj - yi) + xi:
                hit = not hit
        j = i
    return hit

poly = star_polygon()
rows = []
for py in range(SIZE):
    row = []
    for px in range(SIZE):
        covered = 0
        for sy in range(SS):
            for sx in range(SS):
                x = px + (sx + 0.5) / SS
                y = py + (sy + 0.5) / SS
                if inside(poly, x, y):
                    covered += 1
        row.append(round(255 * covered / (SS * SS)))
    rows.append(row)

print("// Generated by tools/gen_star.py -- do not edit by hand.")
print("#pragma once")
print("#include <lvgl.h>")
print()
print(f"#define STAR_IMG_SIZE {SIZE}")
print()
print("static const uint8_t kStarAlpha[] = {")
for row in rows:
    print("    " + " ".join(f"0x{v:02X}," for v in row))
print("};")
print()
print("static const lv_img_dsc_t kStarImg = {")
print("    .header = {.cf = LV_IMG_CF_ALPHA_8BIT,")
print("               .always_zero = 0,")
print("               .reserved = 0,")
print(f"               .w = {SIZE},")
print(f"               .h = {SIZE}}},")
print(f"    .data_size = {SIZE * SIZE},")
print("    .data = kStarAlpha,")
print("};")
